apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: 193382206834.dkr.ecr.us-west-2.amazonaws.com/example-eks:f03d06d40d3365e0cb6b337a3b440bbf55518886
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
