---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-python
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: 193382206834.dkr.ecr.us-west-2.amazonaws.com/example-eks:3f648ae15c9c8550fd9fab8f0cbd93ba4008199f
        #image: REGISTRY/IMAGE:TAG
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
