apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-python
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-python
    spec:
      containers:
      - name: hello-python
        image: 193382206834.dkr.ecr.us-west-2.amazonaws.com/example-eks:a14f9a7a54bf4f23e9a3669e9cc619ccd2dc21ba
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
