apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 193382206834.dkr.ecr.us-west-2.amazonaws.com/example-eks:a54ccc57dda6f10445a75f20b088f3af1fe3ce64
        ports:
        - containerPort: 3000
